export const PHRASES = [
  'elk meat',
  'fiscally conservative',
  'hey Jamie, pull that up',
  'Huawei phones',
  'borders are stupid',
  'lower hominids',
  'pull that sucker right up close to your mouth',
  'sober October',
  'straight up murderer',
  'I fucking killed',
  'stoned ape',
  `it'll fuck you up`,
  `Alex Jones is right more than he's wrong`,
  'keto flu',
  'CBD oil',
  `Lion's Mane mushroom`,
  'coconut oil',
  'I eat elk meat everyday',
  'oh, a hundred percent',
]
