export const PHRASES = [
  'what we really need is a council of elders',
  "it's entirely possible",
  "in some areas, you could kill 100 wolves a day and it wouldn't make a difference",
  'being stoned would make you a better NASCAR driver',
  'I wish Hitler had succeeded in his art career instead of causing WW2',
  'hey Jamie, pull that up',
  'have you ever done DMT',
  'the universe rewards calculated risk and passion',
  'if you can control what you eat, you can control all other aspects of your life',
  'there’s a direct correlation between positive energy and positive results in the physical form',
  'oh, a hundred percent',
  'I was the first to own a sensory deprivation tank',
  'let me tell you something about coyotes',
  'high level problem solving with dire physical consequences',
  'Huawei phones',
  'having one person as president is a terrible way to govern our country',
  'borders are stupid',
  'pull that sucker right up close to your mouth',
  'lower hominids',
  'the New York Times and the sugar industry are bribing scientists',
  'do you know how big a full grown wolf is',
  'we should get rid of the cage entirely and have fights on a basketball court',
  'did you know the frontal cortex is not fully developed until you reach the age of 25',
  'Carlos Mencia steals jokes',
  'I eat elk meat everyday',
  'after we’re done, I’ve got a freezer full of fantastic Elk for you',
  'I bow hunt',
  'do you know about Dimethyltryptamine',
  'my chickens got jacked by a coyote',
  'sober October',
  'keto flu',
  'I have tendonitis in my right elbow',
  'I was reading this article about',
  'young Jamie pull this up',
  'I was at the Comedy Store the other day',
  "It's because of tribalism",
  'Marxism',
  'my friend Jordan Peterson',
  'Jordan Peterson',
  'Bert Kreischer',
  'CBD oil',
  'Onnit',
  "turmeric coffee with Lion's Mane mushroom",
  'David Goggins',
  'Khabib mauls everyone',
  "there's this guy on instagram, that has a pet badger and a rescued coyote",
  "I'm just playing devil's advocate here",
  "Joey Diaz is the funniest Human being I've ever met",
  'that motherfucker banned marijuana and brought pigs to California',
  'coconut oil',
  'medium chain triglycerides',
  "l'll hook you up with that",
  'a popular person actually participated in the popularity contest',
  'easily one of my top 5 comedians of all time',
  'straight up murderer',
  'I fucking killed',
  'stoned ape',
  "it'll fuck you up",
  'Terence McKenna',
  "Lion's mane",
  "I don't care if you're gay, black, Chinese, straight.",
  'When I say something stupid, I’m not thinking about what I’m going to say before I say it.',
  "If you're like 21 years old, and you say to me, should I get vaccinated? I'll go no.",
  'madness of crowds',
  "They've arrested leftists for starting forest fires up there",
]
